stages:
  - build
  - deploy

try-build:
  stage: build
  image: python:3.13-slim-trixie
  script:
    - apt-get update
    # set up Python 3
    - apt-get install -y git python3-pip make
    # install dependencies
    - python3 -m pip install -r requirements.txt
    # create mock develop to allow building
    - ln -s latest develop
    - make latest/version.txt
    # build documentation
    - make build/merged
  artifacts:
    paths:
    - build/merged
